version: "3.8"

services: 
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

    restart: always
    ports:
      - "27018:27017"
    volumes:
      - /home/nog/dev/docker/volumes/mongo:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge